encoding: utf-8
pygments: true
markdown: redcarpet
name: Poly Tech Docs
relative_permalinks: false
baseurl: /
url: /
permalink: /news/:year/:month/:day/:title/
repository: https://github.com/wh1100717/PolyTechDocs
